services:
  - type: web
    name: mysite-django
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn webapp.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: webapp.settings
      - key: PYTHON_VERSION
        value: 3.12
      - key: DATABASE_URL
        fromDatabase:
          name: mydb_eovg
          property: connectionString

databases:
  - name: mydb_eovg
    plan: free